### ISSUE TITLE
Context does not provide getRemainingTimeInMillis function

### ISSUE THREAD

**Issue by Vilsepi** [ashiina/lambda-local#10]
Currently the context library does not provide the getRemainingTimeInMillis function causing an error:

    TypeError: context.getRemainingTimeInMillis is not a function

See here: http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

**Comment by ashiina** [comment]
Thanks. Looks like the Context object has a lot of things to support. 
Let's make this a feature for 0.0.8 - Please send over a pull request if you can!

**Comment by gpotter2** [comment]
Here you are :)
https://github.com/ashiina/lambda-local/pull/11

**Comment by ashiina** [comment]
Thanks @gpotter2 !
This fix will be released now as 0.0.8.
