### ISSUE TITLE
Turn off 'info' logging

### ISSUE THREAD

**Issue by pkosterman** [ashiina/lambda-local#100]
Loving this tool! Very easy to test my lambda-code locally.

I am writing my Lambda functions using Go, using a Node.js wrapper that spawns of a Go process.

For my test cases in Golang, I'd like to execute these by using lambda-test. For this to work, I was wondering if it is possible to add in an option-flag to turn off the additional 'info' & 'error' logging. So instead of having:

<img width="927" alt="screen shot 2017-08-13 at 10 22 31 pm" src="https://user-images.githubusercontent.com/3961740/29250505-fb5f60ba-8075-11e7-890f-e717467b68a3.png">

Would it be possible to just return the raw result:

![alternate-result](https://user-images.githubusercontent.com/3961740/29250511-0e5f96da-8076-11e7-82ac-73ecc55895c3.png)

Additionaly, would it be possible to pass in the JSON event-data as an event-string, instead of passing in a file-path. For example:

lambda-local -e '{"type":"qr","width":100,"height":200,"message":"testingtesting"}'

**Comment by gpotter2** [comment]
Hi,
There was a bug that printed an empty `error`.
It should now be fixed.

You can turn off the `info` logs by using the `setLogger` function, and passing a winston logger with `logger.level='error'`

About the event as a string, it has already been asked and should be available very soon.

**Comment by pkosterman** [comment]
Thanks for your quick response! And good to hear you are working on adding a verbose parameter - will be very helpful.

Let me know if you already started on the event-string, else I can fork of the repo and add that in.

**Comment by gpotter2** [comment]
@quangbuule Has added it in
https://github.com/ashiina/lambda-local/pull/98
However his fork isn't missing some commits. You should get his commit through `git cherry-pick`

**Comment by gpotter2** [comment]
Hi
sorry for the delay, there's now a proper nice verbose system available !
Please have a look at the updated Readme for the parameter `verboseLevel`

Thanks !
