### ISSUE TITLE
Option to display execution time

### ISSUE THREAD

**Issue by petermoser** [ashiina/lambda-local#104]
This library has been very useful so far. One thing that I found missing is to have an option to display the execution time of the lambda function.

**Comment by gpotter2** [comment]
Hi !
Would you prefer having this in the CLI or in the API ? (using the `lambda-local` command, or in from your script) ?
Thanks !

**Comment by gpotter2** [comment]
Added in the CLI

**Comment by petermoser** [comment]
Thanks!!
