### ISSUE TITLE
Timeout is never canceled when calling over API.

### ISSUE THREAD

**Issue by DominikStarke** [ashiina/lambda-local#111]
Hello Friends!
The following code will always run into a timeout error as the timeout is initialized but never cleared.
```
const lambdaLocal = require('lambda-local');
lambdaLocal.execute({
    event: {
      'key': 1,
      'another_key': "Some text"
    },
    lambdaFunc: {
      handler : function (event, context, callback) {
        callback(null, true);
      }
    },
    timeoutMs: 3000,
    callback: function(err, data) {
        if (err) {
            console.log(err);
        } else {
            console.log(data);
        }
    }
});
```
A relatively simple fix should be to assign the error timeout to a variable and clear it when the context succeeds. Or am I missing something?  
I could obviously call process.exit() but that's unfortunately not an option in my program.

**Comment by gpotter2** [comment]
Thanks for reporting !
Should be fixed by now
