### ISSUE TITLE
Environment variables are not supported in event.js files

### ISSUE THREAD

**Issue by cgmartin** [ashiina/lambda-local#120]
It would be cool if environment variables processed by the `-E|--envfile` arguments could also be used within the `event.js` file, ie.:

```
'use strict';
module.exports = {
  'directive': {
    'header': {
      'namespace': 'Alexa',
      'name': 'ReportState',
      'payloadVersion': '3',
      'messageId': '1bd5d003-31b9-476f-ad03-71d471922820'
    },
    'endpoint': {
      'endpointId': `${process.env.TEST_HUBID}-device-97`,
      'scope': {
        'type': 'BearerToken',
        'token': 'access-token-from-skill'
      }
    },
    'payload': {}
  }
};
```

The [event file loading](https://github.com/gpotter2/lambda-local/blob/ef21a38d8d05698631f4db984a6a3f1f38f4b3e3/bin/lambda-local#L96) happens before `./lib/lambdalocal.js` kicks in, where it processes the env var options after the fact.

Thanks for sharing this utility, it has been extremely useful.

**Comment by gpotter2** [comment]
@cgmartin Hi ! Thanks a lot for reporting. This has been fixed in the last (github) version of lambda local !
https://github.com/ashiina/lambda-local/archive/develop.zip
Will soon be on npm.

Thanks !!!
