### ISSUE TITLE
RFE: Better logging for Error objects in CLI

### ISSUE THREAD

**Issue by joebowbeer** [ashiina/lambda-local#124]
I noticed that if my handler passes an Error object to the callback then lambda-local does not log the error's message text.

For example, this handler:

```
exports.handler = function(event, context, callback) {
    return callback(new Error('Failed!'))
}
```

produces the following output:

```
error: End - Error
error: ------
error: {}
error: ------
error: Lambda failed in 170ms.
```

Unlike the following handler:

```
exports.handler = function(event, context, callback) {
    return callback('Failed!')
}
```

which produces more informative output:

```
error: End - Error
error: ------
error: Failed!
error: ------
error: Lambda failed in 170ms.
```

Can you provide better support for Error objects?

**Comment by gpotter2** [comment]
Hi !
Thanks a lot for reporting, this should indeed be working as it's specified in the doc:
http://docs.aws.amazon.com/en_en/lambda/latest/dg/nodejs-prog-mode-exceptions.html

It should now be fixed in the github version of lambda-local !
