### ISSUE TITLE
lambda-local does not wait for empty event loop

### ISSUE THREAD

**Issue by pbostrom** [ashiina/lambda-local#128]
lambda-local does not appear to wait for empty event loop. The below function should log "done" after a 1000ms timeout, but it returns before logging. I've tested with and without the `-n` flag.

```javascript
exports.handler = function(event, context, callback) {
  setTimeout(function() {
    console.log("done");
  }, 1000);
  context.succeed("Success");
}
```

```
$ lambda-local -l wait.js -e examples/event.js
info: START RequestId: 35f859c1-2627-3dd6-0dd0-11792f24eef9
info: End - Message
info: ------
info: Success
info: ------
info: Lambda successfully executed in 9ms.
```

```
$ lambda-local -n -l wait.js -e examples/event.js
info: START RequestId: 751dc0a1-f981-9537-6e8e-880a910be8fa
info: End - Message
info: ------
info: Success
info: ------
info: Lambda successfully executed in 8ms.
```

**Comment by gpotter2** [comment]
Hi, thanks for reporting
This seems to be a bug, however, i'm not sure that it's fixable in `lambda-local`.

I will try to investigate, but I don't see a way to wait for all unregistered setTimeout from outside its caller...

**Comment by gpotter2** [comment]
FTR: I'm waiting for https://github.com/nodejs/node/pull/21102 to be published before using it to fix this issue

**Comment by gpotter2** [comment]
@pbostrom Hello ! I don't know if you remember this issue, or if you still use `lambda-local`, but I finally fixed this.
Could you retry against master ? Your example is now passing

**Comment by pbostrom** [comment]
lgtm

```
$ ./bin/lambda-local -l wait.js -e examples/event_s3-put.js --wait-empty-event-loop
info: START RequestId: 4958dd18-ef2b-df40-0e68-8043bba2bbbe
info: End - Message
info: ------
info: Success
info: ------
done
info: Lambda successfully executed in 1054ms.
```
