### ISSUE TITLE
lambda-local forces AWS_REGION and AWS_DEFAULT_REGION variables to `us-east-1`

### ISSUE THREAD

**Issue by dimkir** [ashiina/lambda-local#130]
lambda-local forces AWS_REGION and AWS_DEFAULT_REGION variables to `us-east-1`  regardless of what value environment variables AWS_REGION or AWS_DEFAULT_REGION  hold within the active shell session.

#### Example

Let's open fresh bash session, which already has some AWS environment variables preset. 

Below you can see that current shell session has value `eu-west-1` for `AWS_REGION` and `AWS_DEFAULT_REGION` variables
```
$ env | grep AWS
AWS_PROFILE=dimkir-admin-profile-test
AWS_DEFAULT_REGION=eu-west-1
AWS_DEFAULT_PROFILE=dimkir-admin-profile-test
AWS_REGION=eu-west-1
```

And now as a next command,  let's run in the same shell lambda-local with test file `env.js` (see code below):

```
$ lambda-local -l env.js -e events/empty.json 
info: START RequestId: 119f99ab-f546-03c3-23d6-b9672569f572
AWS Environment vars: 
 { AWS_PROFILE: 'dimkir-admin-profile-test',
  AWS_DEFAULT_REGION: 'us-east-1',
  AWS_DEFAULT_PROFILE: 'dimkir-admin-profile-test',
  AWS_REGION: 'us-east-1',
  AWS_LAMBDA_FUNCTION_NAME: 'handler',
  AWS_LAMBDA_FUNCTION_MEMORY_SIZE: '1024',
  AWS_LAMBDA_FUNCTION_VERSION: '1.0',
  AWS_EXECUTION_ENV: 'AWS_Lambda_nodejs' }
info: End - Message
info: ------
info: Finished
info: ------
info: Lambda successfully executed in 10ms.

```

When running lambda-local, we can see that actual `env.js` code received correctly value of some variables, eg:  AWS_PROFILE and AWS_DEFAULT_PROFILE from the current shell session. However lambda-local **forced values of AWS_REGION and AWS_DEFAULT_REGION** to `us-east-1` (which should should have been `eu-west-1` as per current shell session)

---
Here's code for `env.js`, which simply prints environment variables starting with `AWS`

```
// env.js

let aws_environment_variables = {};
for(let key in process.env ){
    if ( 0 === key.indexOf('AWS')) 
      aws_environment_variables[key] = process.env[key];
}
console.log(`AWS Environment vars: \n`, aws_environment_variables);

exports.handler = (event, context, callback)=>{
    callback(null,'Finished');
};
```

**Comment by gpotter2** [comment]
Thanks for reporting and sorry for the late answer.
Fixed
