### ISSUE TITLE
Context.done(err, message)  modified the err argument

### ISSUE THREAD

**Issue by danzGentrack** [ashiina/lambda-local#133]
The err argument is reassigned inside Context.done(err, message) .  An error thrown from a lambda function become different after passing through lambda-local.  This is unexpected.
```
..
err = {
  errorMessage: err.error,
 ....
}
```

**Comment by gpotter2** [comment]
Hi !

This is expected: according to 
https://docs.aws.amazon.com/en_en/lambda/latest/dg/nodejs-prog-mode-exceptions.html
Any error passed to `context.done` will be serialized and sent according the previously shown format.

Feel free to ask any other questions,
Greetings

**Comment by danzGentrack** [comment]
Yeah, you are right. Thanks for your help.
