### ISSUE TITLE
Read default AWS_REGION in the shared config file

### ISSUE THREAD

**Issue by DreamSworK** [ashiina/lambda-local#141]
For AWS_REGION detection you use this method from **lib/lambdalocal.js** [76 line]:

`process.env['AWS_REGION'] = region || process.env['AWS_REGION'] || 'us-east-1';`

It will be work correctly only if you manual set up the region using the AWS_REGION global environment variable.

So, you should use an additional detection from the shared config file:

**Linux, macOS, Unix:** `~/.aws/config`
**Windows:** `C:\Users\USER_NAME\.aws\config`

**Comment by gpotter2** [comment]
Thanks for reporting! This is indeed something we should be supporting.

In the meantime, you can explicitly use this config file using the `--profile-path ~/.aws/config` (CLI) option or using `profilePath` (API)

PS: I allowed me to change the title of the issue, to reflect the real content of the issue

**Comment by DreamSworK** [comment]
Yes, it works for me. Thanks.

**Comment by gpotter2** [comment]
Merged to ashina/develop.
Will be in next release
