### ISSUE TITLE
Would it be possible to generate a new awsRequestId with every invocation?

### ISSUE THREAD

**Issue by bootylactin** [ashiina/lambda-local#148]
When requiring in lambda-local to a test file

`var lambdaLocal = require( 'lambda-local' );`

and running

`lambdaLocal.execute()`

multiple times for _n_ tests, it returns the same awsRequestId for every invocation.  We have logging that uses the awsRequestId to bundle all logs from the same call together in a package which subsequently is sent to a Slack channel.

I was able to hack something together by removing the self invoking nature of the Context.createInvokeId function in context.js, but it wasn't pretty.

Is there a reason createInvokeId is only executed once, and if not, would it be possible to generate a new awsRequestId with every invocation?

Thanks,

Jon

**Comment by bootylactin** [comment]
Actually, my "hack" wasn't all that terrible, but you may prefer a better way. I'll submit a Pull Request of the changes I made tomorrow, and you can decide whether you'd like to use it.

**Comment by gpotter2** [comment]
Hi @bootylactin,

This should be fixed in https://github.com/ashiina/lambda-local/pull/149

The real issue was that `context` was a class that was not really reset between runs (https://github.com/ashiina/lambda-local/issues/79).

**Comment by bootylactin** [comment]
Works beautifully, thanks so much!
