### ISSUE TITLE
SignatureDoesNotMatch errors with v1.4.8+

### ISSUE THREAD

**Issue by zoul0813** [ashiina/lambda-local#157]
I upgraded from 1.4.7 to 1.5.1 and all my local tests failed, stating "SignatureDoesNotMatch".

When downgrading back to 1.4.7, everything works as expected.  I tried 1.4.8, 1.5.0 and 1.5.1 with the same result.

**Comment by gpotter2** [comment]
Hello, thanks for reporting.
Do you have any short code sample / test / anything you could share so I can investigate ?

Thanks !

**Comment by zoul0813** [comment]
@gpotter2 far as I can tell, the region is being set properly.  I'm actually passing the region parameter into the service constructors manually:

```const sqs = new AWS.SQS({ region: 'us-east-1' });```

My `~/.aws/config` also has the access/secret/region set correctly for the `default` (and only) profile, my `~/.aws/credentials` does not have a region variable set and `AWS_REGION` does not exist in my application or shell environment vars.

Here's a test script I put together:

```
const AWS = require('aws-sdk');
const sqs = new AWS.SQS({ region: 'us-east-1' });

exports.handler = function(event, context, callback) {
    sqs.receiveMessage({
        QueueUrl: TASK_QUEUE_URL
    }).promise().then((messages) => {
        console.log(JSON.stringify(messages, null, 2));
        return callback(null, 'DONE');
    }).catch((err) => {
        return callback(err);
    });
};

if(process.env.TEST == 1) {
    console.log(process.env);
    exports.handler({}, {}, (err, response) => {
        if(err) console.error(err);
        console.log(response);
    });
}
```

If I execute this script manually, it works and returns my queue messages ...

`$ TEST=1 node index.js`

If I use lambda-local, it fails with the SignatureDoesNotMatch exception:

`lambda-local -l index.js -e sample-event.json`

The sample-event.json is an empty object, it only contains `{}`.

**Comment by gpotter2** [comment]
Closed for inactivity. Feel free to reopen
