### ISSUE TITLE
Local Lambda function calling another local lambda function

### ISSUE THREAD

**Issue by stevenmilstein** [ashiina/lambda-local#159]
I have a similar problem as described here in [Support one Local Lambda calling another Local Lambda scenarios · Issue #510 · awslabs/aws-sam-cli](https://github.com/awslabs/aws-sam-cli/issues/510)

I can successfully invoke a local lambda function except when that function calls another lambda. The problem occurs when the subsequent function is called, AWS prepends FunctionName with the Amazon Resource Name (ARN). 

Which according to [Invoke - AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html), may be the intended behaviour.
>  FunctionName
> 
>     The Lambda function name.
> 
>     You can specify a function name (for example, Thumbnail) or you can specify Amazon Resource Name (ARN) of the function (for example, arn:aws:lambda:us-west-2:account-id:function:ThumbNail).
> 

The problem is `FunctionName: Thumbnail` is invoked as ` arn:aws:lambda:us-west-2:account-id:function:ThumbNail`, resulting in `"errorMessage": "Function not found: arn:aws:lambda:us-west-2:account-id:function:ThumbNail"`

Are you aware of workarounds when configuring `new aws.Lambda();`, or, are you dependent on [Issue #510 · awslabs/aws-sam-cli](https://github.com/awslabs/aws-sam-cli/issues/510)?

Thanks in advance for your time.

**Comment by gpotter2** [comment]
Hi.
Sorry I am a bit confused. Are you sure that you are on the right project page ? This is not aws-Sam-cli

**Comment by stevenmilstein** [comment]
Sorry for the confusion. My understanding is that lambda-local is dependent on AWS SAM CLI. 

If that's true, then it looks like the problem is rooted with AWS and lambda-local will hopefully be able to implement the solution, at some point.

If that's not true, then perhaps you can help me get past the FunctionName being prefixed with the ARN.

Thanks

**Comment by gpotter2** [comment]
Well this project is not based on aws-sam-cli, and is made for unit tests / scripts.

Nested functions work quite well here, for instance from our tests

```
var lambdalocal = require("../lib/lambdalocal.js");
            lambdalocal.setLogger(winston);
            lambdalocal.execute({
                event: require(path.join(__dirname, "./events/test-event.js")),
                lambdaPath: path.join(__dirname, "./functs/test-func.js"),
                lambdaHandler: functionName,
                callbackWaitsForEmptyEventLoop: false,
                timeoutMs: timeoutMs,
                callback: function (err, done) {
                    assert.equal(done.result, "testvar");
                    //Second run
                    lambdalocal.execute({
                        event: require(path.join(__dirname, "./events/test-event.js")),
                        lambdaPath: path.join(__dirname, "./functs/test-func.js"),
                        lambdaHandler: functionName,
                        callbackWaitsForEmptyEventLoop: false,
                        timeoutMs: timeoutMs,
                        callback: function (_err, _done) {
                            assert.equal(_done.result, "testvar");
                            cb();
                        },
                        verboseLevel: 0
                    });
                },
                verboseLevel: 0
            });
```

We don’t prefix the function name with anything :/

**Comment by stevenmilstein** [comment]
Thanks for the reply & explanation.

In my case, I'm not nesting lambdalocal.execute, as in your example. My script calls lambdalocal.execute which calls a lambda function successfully. However if that lambda function calls another lambda function it fails.

``` 
test.js 
  -> lambda.execute(FunctionName1) - works
     -> FunctionName1 calls FunctionName2 - fails because AWS prefixes FunctionName with ARN.
```

Thanks for your help

**Comment by gpotter2** [comment]
Hi, sorry I forgot about this issue.

There has been quite many changes since August 2018 :smile: Are you still using `lambda-local` (therefore have you been able to resolve your issue) ? Otherwise could this be closed ?

Thanks !

**Comment by stevenmilstein** [comment]
Thanks for following up. I'm no longer on that project so please close this
issue.
