### ISSUE TITLE
Support of the runtime v4.3

### ISSUE THREAD

**Issue by vfedoroff** [ashiina/lambda-local#16]
Lambda local doesn't support a new programming model: http://docs.aws.amazon.com/lambda/latest/dg/programming-model.html.

For example: Lambda function, that uses the new model:

exports.handler = function(event, context, callback) {
  callback(null, "some success message");
};

Return following error:

> Logs
> ----
> START RequestId: 87968b45-8119-cba1-2d35-72e55c04e7bb
> 
> /lambda/app.js:2
>   callback(null, "some success message");
>   ^
> TypeError: undefined is not a function
>     at Object.exports.handler (/lambda/app.js:2:3)
>     at /usr/lib/node_modules/lambda-local/bin/lambda-local:54:27
>     at Object.<anonymous> (/usr/lib/node_modules/lambda-local/bin/lambda-local:56:3)
>     at Module._compile (module.js:456:26)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:935:3

**Comment by vfedoroff** [comment]
Here is the pull request with the fix: https://github.com/ashiina/lambda-local/pull/17.

**Comment by ashiina** [comment]
Merged #17 ! Thank you @vfedoroff :)
