### ISSUE TITLE
Context was removed since 1.4.6

### ISSUE THREAD

**Issue by tonylgen** [ashiina/lambda-local#160]
It is not backwards compatible to remove `context` from lambdalocal.js as I figured out that my unit tests ues `.context.awsRequestId` to validate the request id sometimes. Any thoughts behind this change (removing context)?
Is there an alternative way to get `awsRequestId` in the later versions? If not, is that a problem to put it back?

My code is like this:
```
            ...
            const lambda = require("lambda-local");
            return lambda.execute({
                event,
                lambdaPath: `${__dirname}/..`,
                verboseLevel: 0,
            }).then(
                (result: any) => {
                    expect.fail();
                },
                (err: Error) => {
                    expect(err.message).to.equal(JSON.stringify({
                        details: "An application with the name already exists",
                        message: "Bad Request",
                        requestId: lambda.context.awsRequestId,
                        statusCode: 400,
                    }));
                },
            );
```

Commit that removed context: https://github.com/ashiina/lambda-local/commit/081b96834c88ac5a4db9803774122b57a91b88f0

**Comment by gpotter2** [comment]
We recently turned the context object, from static to a prototype.

This allows nested lambda-local calls. Because the object is not static anymore, it make no sense to make it statically available, as it could suddenly change during execution (nested calls)

We could however return it in the promises. So you would get several args, including the context.

Would that suits your case ?

**Comment by tonylgen** [comment]
hi @gpotter2 , thanks for the info. I think that suits my case as long as I can get the context :)
Has the change you mentioned been done?

**Comment by gpotter2** [comment]
Sorry had no time to do so before. Will try to work on It ASAP

**Comment by gpotter2** [comment]
It is know possible to pass a custom context: https://github.com/ashiina/lambda-local/commit/2e5a39c06fc8a18a83acd5fadaaac917fa45dd26

Acquiring the context after the run isn't supported as of today. Feel free to contribute
