### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by rdm** [ashiina/lambda-local#162]
_outputJSON in lambda-local/lib/utils.js uses JSON.stringify, but if there's an http error, Context.prototype.fail can be passed an err value which is a node IncomingMessage (which is a circular structure).

This prevents lambda-local from reporting on that error in a meaningful fashion. (In other words, instead of a report on a 4xx http error, you get informed about a type error.)

**Comment by gpotter2** [comment]
Thanks for reporting ! I implemented you idea in https://github.com/ashiina/lambda-local/pull/165
