### ISSUE TITLE
Is there a way to pass in clientContext?

### ISSUE THREAD

**Issue by wrightnathan** [ashiina/lambda-local#166]
I am trying to test a lambda that requires information about the user passed to be included in ClientContext.

```
var clientContextBuffer = new Buffer(JSON.stringify(clientContext)).toString('base64')

  var params = {
    ClientContext: clientContextBuffer,
    FunctionName: lambdaName,
    InvocationType: 'RequestResponse',
    LogType: 'Tail',
    Payload: JSON.stringify(eventPayload)
  }
```

Is there a way to pass ClientContext when executing lambda-local?

**Comment by gpotter2** [comment]
(Sorry for not answering earlier), thanks for the report and PR

Closed by https://github.com/ashiina/lambda-local/issues/167
