### ISSUE TITLE
Time out Error - uncaughtException: Task timed out 

### ISSUE THREAD

**Issue by thilinadinith** [ashiina/lambda-local#173]
This library gives an error what ever the lamda that im excuting is ( even simple lambda with console log gives following error ) 

`

>  uncaughtException: Task timed out after 3.00 seconds date=Mon Jan 07 2019 10:02:17 GMT+0000 (UTC), pid=17229, uid=502, gid=20, cwd=/Users/Thilina/github/lamda-avatar-compressor, execPath=/usr/local/bin/node, version=v8.9.0, argv=[/usr/local/bin/node, /usr/local/bin/lambda-local, -l, index.js, -h, handler, -e, test.json, -E, {"secret":"value","key2":"value2"}], rss=50872320, heapTotal=20291584, heapUsed=14305120, external=371450, loadavg=[2.80859375, 2.51611328125, 2.60205078125], uptime=272549, trace=[column=15, file=/usr/local/lib/node_modules/lambda-local/lib/context.js, function=null, line=124, method=null, native=false, column=11, file=timers.js, function=ontimeout, line=475, method=null, native=false, column=5, file=timers.js, function=tryOnTimeout, line=310, method=null, native=false, column=5, file=timers.js, function=Timer.listOnTimeout, line=270, method=listOnTimeout, native=false], stack=[TimeoutError: Task timed out after 3.00 seconds,     at Context.<anonymous> (/usr/local/lib/node_modules/lambda-local/lib/context.js:124:15),     at ontimeout (timers.js:475:11),     at tryOnTimeout (timers.js:310:5),     at Timer.listOnTimeout (timers.js:270:5)]

`

**Comment by gpotter2** [comment]
Your lambda timed out. It might be taking too long or you are wrongly passing the parameters to lambda local. Please follow the examples on the README or in the test files.

**Comment by gpotter2** [comment]
Closed for inactivity
