### ISSUE TITLE
Error: Cannot find module 'aws-sdk' (REDUX(

### ISSUE THREAD

**Issue by shaunhurley** [ashiina/lambda-local#175]
Hi,

I very much appreciate your work with Lambda-Local, I use it a lot for local testing and it is a great time saver.

As you are aware, a Lambda function on AWS automatically has access to 'aws-sdk' and your documentation specifically says:

_"Since the Amazon Lambda can load the AWS-SDK npm without installation, Lambda-local has also packaged AWS-SDK in its dependencies. If you want to use this, please use the "-p" option with the aws credentials file."_

However I am unable to have my project automatically pick up your included aws-sdk module.

- I am able to use the -p and -P switches to specify may aws credentials file
- The aws-sdk is included in the lambda-local\node_modules directory 

Am I missing something? Or do we still have to use the 'npm link' function to create a symlink back to your included 'aws-sdk' package, and then exclude the symlink when zipping up an upload package to prevent it from being copied in?

Thanks for your time!

Shaun Hurley

**Comment by gpotter2** [comment]
Hi, thanks for your interest for this project !

All this means is that we have
```
"dependencies": {
    "aws-sdk": "^2.1.6",
    [...]
},
```
Meaning that you should be able to `require("aws-sdk")` from within the handler.

We're not doing much on that side :smile:

I'm not sure to understand what your issue is :/ What do you mean by "automatically picked up" ?

**Comment by shaunhurley** [comment]
I guess I am a little confused.  I can deploy a package to AWS that includes a  `"const aws = require('aws-sdk');` statement, and it works even though I haven't included the aws-sdk in the deployment package, because every Lambda automatically has the aws-sdk included.
 
I took the lambda-local documentation to mean that I could do the same thing, that I could use the `"const aws = require('aws-sdk');` statement, and lamba-local would reference the aws-sdk that is deployed as part of the lambda-local package.

It appears that is not the case, correct?  I still  have to either locally install the aws-sdk, or create a symlink to it, and then manually exclude it from my deployment packages?

Thanks,

Shaun

**Comment by gpotter2** [comment]
I've added an example to the tests: https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L266 while releasing 1.6.1.

You shouldn't need to install `aws-sdk` as it is a dependency of `lambda-local`. It should get installed as well

**Comment by shaunhurley** [comment]
Thanks, I've updated to 1.6.1 and I can see the test-func-aws-sdk.js.  The aws-sdk package is definitely still installed under npm in ...\npm\node_modules\lambda-local\node_modules\aws-sdk (it was previously as well).

Forgive my ignorance, but what is the best way to execute the test suite?  Do I need to fork the repository and make it locally?  Or can I invoke it just with the npm lambda-local package installed?

**Comment by gpotter2** [comment]
You should `npm install lambda-local` (Add it to your `package.json` ? Or use `-g`), then use it as a library:

`var lambdalocal = require("lambda-local")`

If you want further help, as this is technically unrelated to this project, please prefer a forum such as StackOverflow :-)

**Comment by gpotter2** [comment]
Closed for inactivity, and because it's probably unrelated to lambda local itself
