### ISSUE TITLE
getSessionAttributes is not a function

### ISSUE THREAD

**Issue by cgazzola** [ashiina/lambda-local#179]
Hi, I want to start off by saying I appreciate your work with lambda-local.

That being said, I'm trying to write some tests for an Alexa skill by using lambda-local. I am able to hit the lambda/handler I want to test by using `lambalocal.execute({});`but as soon as I try to get the session attributes for the skill by using one of the methods provided by the ask-sdk `attributesManager.getSessionAttributes();`, I get the error "getSessionAttributes" is not a function. I'm providing the path to my AWS credentials and profile name as options within lambdalocal.execute({}).

I'm confused because I read on a blog somewhere that I could use lambda-local to to test my Alexa skill's lambda functions locally. I have tried to install the ask-sdk into lambda-locals package.json, but I got the same error.

**Comment by gpotter2** [comment]
Hi !
Could you provide a short code snippet and a file architecture that would replicate the issue (what files are used, the file tree) ?

Also please check that you're using the last version (released yesterday)

Thanks !

**Comment by cgazzola** [comment]
Yes! The handler that is erroring out is the one called 'handle':

```
const MyHandler = {
     canHandle(handlerInput) {
          return handlerInput.requestEnvelope.request.type === 'IntentRequest'
              && handlerInput.requestEnvelope.request.intent.name === 'MyHandler'
     } async handle(handlerInput) {
          const {responseBuilder, attributesManager} = handlerInput;
          let sessionAttributes = attributesManager.getSessionAttributes();
     
          return responseBuilder
               .speak("Thank you!")
               .withShouldEndSession(false)
              .getResponse();
       }
};
```

In my testing file, I am able to import this lambda function by doing:
`const lambdaFunc = require(...path/to/MyHandler).MyHandler;`

There are other handlers in this file, so that's why I am using a period to just grab 'MyHandler'.
For the lambdaHandler option, I'm passing 'handle'. Everything works fine until it hits the .getSessionAttributes() method, which is part of the ask-sdk-core. It errors out saying "getSessionAttributes is not a function". When I deploy this lambda to AWS, it works fine.

The event I'm sending in his a mocked out version of handlerInput, which is just a giant json object.

My lambdalocal.execute looks like this:

```
lambdalocal.execute({
     event: event,
     lambdaFunc: lambdaFunc,
     region: region,
     profilePath: 'path/to/aws/credentials',
     profileName: 'my_profile_name',
     callbackWaitsForEmptyEventLoop: false,
     timeoutMs: 3000,
     callback: cb
});
```


The file structure is like a typical node project structure. Under root there is a directory for lambdas, and a directory for tests (which is where I am writing a test that uses lambda-local). The package.json at the root level contains all the dependencies I need for testing, including lambda-local. The package.json under the lambda directory has other additional dependencies.

I will check the latest version! Thank you.

**Comment by gpotter2** [comment]
We don't support ASK-SDK as of right now :/

That's something that would be great to have, but doesn't fit in the basic "AWS lambda" case we handle

**Comment by hoegertn** [comment]
You may want to have a look at https://github.com/taimos/ask-sdk-test which serves exactly this purpose and uses lambda-local underneath.

**Comment by gpotter2** [comment]
Thanks @hoegertn for the support !

I'll add a link to that on the README :smile:
