### ISSUE TITLE
What is the right way to make the lambda-local to fail a test case with mocha?

### ISSUE THREAD

**Issue by chakwok** [ashiina/lambda-local#182]
Hi Ahmad Shiina,

I am not able to get a test-case to fail, based on the response I got from the lambda.

In both of the situation I want it to fail, it is not failing the test cases for either callback('failed', null) or callback(null, 'success').

So, what is the right way to make the lambda-local to fail a test case?

```
it('db should have a user of uId: 123',  async function () {
  lambdaLocal.execute({
    event: makeUserEvent({userId: '123'}),
    callbackWaitsForEmptyEventLoop: false,
    lambdaPath,
    callback: function(err, data) {
      if(err) {
        console.log(1)
        expect.fail(null, null, 'You are not supposed to be here') //should fail here
      } else {
        console.log(2)
        // some checking here, may fail or may not fail
        expect.fail(null, null, 'return fail if the userId is 234') //should fail here too
      }
    }
  });
  console.log(3)
})
```
Thanks.

**Comment by gpotter2** [comment]
This is probably more an issue related to your tests manager rather than lambda-local.

If the `expect.fail` calls are the issue, that's not lambda-local.

**Comment by chakwok** [comment]
Hi @gpotter2,

I think the issue has to do with putting the expect.fail inside the callback function, but I am not sure how to correct it.

For the expect.fail, I am actually using [BDD style assertion](https://www.chaijs.com/api/bdd/#method_fail) from chai (sorry for not specifying that). 
What expect.fail(null, null, 'msg') does is just failing the test case without any checking. So, I think the issue is not relevant to the tests manager.

**Comment by gpotter2** [comment]
I see.
I'm not sure why such a test wouldn't fail. We use a lot of similar tests over
https://github.com/ashiina/lambda-local/blob/develop/test/test.js
Which are written almost like yours.

It might have to do with the fact that you are using an async function. Maybe retry without or with promises ?

**Comment by chakwok** [comment]
@gpotter2 

I tried removing the async and using the traditional done(). The result remains the same. I also tested putting the expect.fail(...) line after console.log(3), that way the test is able to fail. 

Code
```
    it('db should have a user of uId: 123',  function (done) {
      lambdaLocal.execute({
        event: makeUserEvent({userId: '123'}),
        callbackWaitsForEmptyEventLoop: false,
        lambdaPath,
        callback: function(err, data) {
          if(err) {
            console.log(1)
            expect.fail(null, null, 'You are not supposed to be here')
            done()
          } else {
            console.log(2)
            expect.fail(null, null, 'return fail if the userId is 234')
            done()
          }
        }
      });
      console.log(3)
      // expect.fail(null, null, 'return fail if the userId is 234')
    })
```

Error Message:
```error: End - Error:
error: error message return from aws lambda
1
3
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (E:\workspace\...)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7)
```

Return from Lambda
`callback('error message return from aws lambda');
`

**Comment by chakwok** [comment]
I debugged further and found that if I put the done() after the supposedly failing assertion, the done() never gets executed. It just breaks the callback and go outside of the lambdaLocal.execute() (without failing of course).

p.s. The test case passes as expected when I put the done() before the the supposedly failing assertion.

**Comment by chakwok** [comment]
It turns out that there's nothing to do with the async or whatever. It worked after I removed the .node_module directory and npm install again.. 

Thanks for helping @gpotter2

**Comment by chakwok** [comment]
The same problem reappears again...

**Comment by gpotter2** [comment]
It's probably not related to lambda-local.
I can't reproduce and apparently you also can't reproduce consistently :/
