### ISSUE TITLE
Lambda Layers

### ISSUE THREAD

**Issue by rbenal** [ashiina/lambda-local#183]
There is support for lambda layers ? or any advice to work with layers using lambda-local ?

**Comment by gpotter2** [comment]
As of today, no.

From what I understand, layers only consist in extracting a zip file to `/opt`.You could probably automate that in a single bash call. It's also probably doable within NodeJS with `fs` calls and some unzip library.

**Comment by rbenal** [comment]
@gpotter2 thx for your answer, yes, layers only consist in extracting zip files to /opt dir, that is not a problem, my question is about to find a good way to develop locally and using lambda-local, at the moment the solution that I'm using is to create a symbolic link to /opt/nodejs an then in my code:

`const m=require('/opt/nodejs/myFileToImport')` [this way my code works on AWS and locally too]

if i don't make this symbolic link i have to put in my code this: 

`const m=require('/Path/to/My/FileToImport')`[this does not work when I deploy the code to AWS].I
but with this solution i have to change the symbolic link with each project ... so my question is which is the best approach to work with lambda-local and layers? Thanks!

**Comment by gpotter2** [comment]
Your approach seems fine. I'm not sure I could be of much help from within lambda local
(Sorry for the delay btw)
