### ISSUE TITLE
Support for source mapping

### ISSUE THREAD

**Issue by schof** [ashiina/lambda-local#188]
It would be cool if lambda-local supported source mapping so we could make better use of stack traces

**Comment by gpotter2** [comment]
Hi,
Thanks for the suggestion. Could you point to a doc / examples of what you mean by that ?
Thanks

**Comment by schof** [comment]
We're using Typescript which is "compiled" into regular Javascript and then also combined with other libraries and minified using Webpack. The result is a minified file and a much larger [source map](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map).The resulting file is a very ugly, difficult to read source file (but nice and light for lambda upload, etc.)

There is a way to show the original line numbers, etc. in any stack traces that are generated but I'm not sure exactly how it's done (just that it can be done.) Javascript tools like [Sentry.io](https://docs.sentry.io/platforms/node/sourcemaps/) allow you to reference a source map so that they can show you the original line numbers, etc. in the stack trace.

**Comment by gpotter2** [comment]
FTR project has now migrated to TypeScript therefore creating a source map should be easily manageable with `tsc --declarationMap`..

**Comment by jcollum-nutrien** [comment]
there's a tool that solves this easily: `source-map-support` -- node's intrinsic source map support doesn't seem to work well with lambda-local
