### ISSUE TITLE
No support for Typescript syntax?

### ISSUE THREAD

**Issue by jamesliupenn** [ashiina/lambda-local#197]
I am attempting to run `lambda-local` via the CLI and I'm running into these `Unexpected token` errors. The only thing I'm doing differently is that my Lambda is written in Typescript. 

This is what I'm executing:
```
lambda-local -l src/lambdas/index.ts -h graphql -e src/lambdas/event_s3.ts
```
`index.ts` is simply a 3 liner index file:

```
import { GraphQLHandler } from "./graphql";  <--- This is where my handler is being created
export * from "./graphql";
export const graphql = GraphQLHandler;
```

What am I doing wrong here? The stacktrace looks to be erroring out on the `{}` around `GraphQLHandler`

**Comment by gpotter2** [comment]
You have to transpile your typescripts files into javascript first before using lambda-local.
that's always in the case in typescript.
See https://stackoverflow.com/a/54410381
