### ISSUE TITLE
pass payload to the handler via request body

### ISSUE THREAD

**Issue by patrick-tresp** [ashiina/lambda-local#204]
Hi i just stumbled over this repo and installed and configured and it works perfectly when passing payload within the script.

i would like "pass payload to the handler via request body" as stated here: https://github.com/ashiina/lambda-local#running-lambda-functions-as-a-http-server . 

Basically i set it up to:

```
const lambdaLocal = require('lambda-local')
const path = require('path')

lambdaLocal
	.execute({
                event: "?????", // <-- how can i pass the received payload from curl or any other request?
		lambdaPath: path.join(__dirname, '../../bin/lambda/router.js'),
		profilePath: '~/.aws/credentials',
		profileName: 'development',
		timeoutMs: 3000,
	})
	.then(function (done) {
		console.log(done)
	})
	.catch(function (err) {
		console.log(err)
	})
```

But ow can i access the payload which has been sent to lambda-local-server?

Is there any example which i did not see?

i thank you for your help!
Patrick

**Comment by gpotter2** [comment]
You're supposed to use `lambdaLocal.watch([the options dict], port)`. You can then use the `callback` options to get the context. You can't use a promise in this case.

You are right this isn't documented

**Comment by patrick-tresp** [comment]
Hey, thank you for your answer, but i think i did not get the correct advise here to use it.

Are you saying that it should be implemented like this:

```
lambdaLocal.watch(
	{
		lambdaPath: path.join(__dirname, '../../bin/lambda/router.js'),
		profilePath: '~/.aws/credentials',
		profileName: 'development',
		timeoutMs: 3000,
	},
	8008
)

```

Sorry to bother, but i also checked the implementation and can only see references to opts.port which is part of the options and not second parameter for watch.

Do you see a chance to share an example for this? i do not find a correct implementation solution with reverse engineering here.

Thanks a lot!

Patrick

**Comment by patrick-tresp** [comment]
Basically i mixed options assignment and this does not work, either passing per commandline or via JSON-Options ist working.

I have it running now with:

```lambda-local -l bin/lambda/index.js -P ~/.aws/credentials -p development --watch 8008 --envfile .env.test```
