### ISSUE TITLE
Only POST requests allowed?

### ISSUE THREAD

**Issue by patrick-tresp** [ashiina/lambda-local#205]
We are running API Gateway which offers by nature multiple http-methods ( GET, POST, PATCH, DELETE … )

Is there a reason why lamda-local is only accepting `POST` as method?

I see this in compiled sources:

```
if (req.method !== 'POST')
                        throw 'Invalid http method (Expected POST)';
```

and i wonder if this is made on purpose or if contribution is appreciated to handle all http-Methods?
With this only a small part of lambda calls can be executed locally.

Thanks,

Patrick

**Comment by gpotter2** [comment]
Hi & sorry for the late reply.
This could probably be fixed to support all HTTP methods, feel free to submit a PR 😄

**Comment by gpotter2** [comment]
Fixed in https://github.com/ashiina/lambda-local/commit/e9aee8987762fb1af3aa18572fc6e5ff10f508cc#diff-605bbc827f3a333b54408f8ff49cf31f81d19a966e0120353e91cb2cbe0da8c6
