### ISSUE TITLE
CLI does not work on Windows 10

### ISSUE THREAD

**Issue by AllanOricil** [ashiina/lambda-local#206]
I tried to run my lambda and it always returned the same as "--help". It just does not start.

![image](https://user-images.githubusercontent.com/55927613/91645171-415e4300-ea19-11ea-9b33-13c7ca889505.png)

**Comment by gpotter2** [comment]
That's what `-h` does :p

**Comment by AllanOricil** [comment]
> That's what `-h` does :p

@gpotter2 the problem was that I was not passing the -e flag and the file, thus it was always showing the same as the --help command, instead of showing an error message, like "you are missing the -e flag/file"
