### ISSUE TITLE
Make aws-sdk dependency optional

### ISSUE THREAD

**Issue by eduardoboucas** [ashiina/lambda-local#209]
Hi! We use `lambda-local` in the [Netlify CLI](https://github.com/netlify/cli) to provide a local environment for serverless functions. Unfortunately, having the AWS SDK as a dependency significantly contributes to our package size, despite the fact that we don't interact with it at all.

I understand that this is required by some of your users and we definitely wouldn't want to disrupt that, but I was wondering if you'd consider publishing a second package without this dependency to accommodate folks who don't need the AWS interaction and could benefit from a smaller payload?

If you're okay with this, I'd be happy to put together a PR with a workflow that automates this process, so that having this second package wouldn't mean additional overhead for the project maintainers.

Thanks in advance!

**Comment by gpotter2** [comment]
Hi, this sounds great, feel free to provide a PR anytime.

We only include `aws-sdk` because it is already included on AWS lambdas, but TBF we could just remove the dep entirely and ask people to download it themselves... If you have a better way that's cool too.
