### ISSUE TITLE
Proposed functionality: Allow stack size to be set/overridden in command line

### ISSUE THREAD

**Issue by collinstowell** [ashiina/lambda-local#21]
It seems locally the stack size default is different than in the lambda environment. Being able to set the size of the stack in the command line would fix this issue. You can currently do this when invoking node via the --stack-size=* command line option. I can only assume there's a way to do this with lambda-local that i'm unaware of, but if you could add in the option to set it via a command line argument, that would be greatly appreciated.

**Comment by ashiina** [comment]
You can do so by calling lambda-local like this:
```
node --stack-size={bytes} lambda-local ...
```

I agree that it would be cool if lambda-local can take it in as a command line arguments, but it may not be as easy as it seems.
Currently the `bin/lambda-local` file is a node.js script, so it can't take in `--stack-size=` as an argument (you have to add this option when you first call the node.js script).
So a fix would be to make `bin/lambda-local` a shell script that calls `node --stack-size={bytes} lambda-local` .
The implementation itself isn't hard, but this will be a breaking change for anybody who is calling `node bin/lambda-local` . So I want to be sure that it is an acceptable change.

Do you think you can create a Pull Request with the implementation? Then we can get the discussion started.

**Comment by gpotter2** [comment]
I don't think this function is useful...

Even with long code, the default nodejs stack size is enough if your program is well codded. If your code use too much memory, it surely is your code's fault.

As said here:

http://stackoverflow.com/questions/20936486/node-js-maximum-call-stack-size-exceeded

> You should wrap your recursive function call into a
> - setTimeout,
> - setImmediate or
> - process.nextTick

> function to give node.js the chance to clear the stack. If you don't do that and there are many loops without any real async function call or if you do not wait for the callback, your RangeError: Maximum call stack size exceeded will be inevitable.

You should review your code to match those advices.

In some cases, if your code is really big (which would be strange for a lambda, due to the execution time) then you might want to increase the stack size, but it shouldn't be necessary...

To do that, the 
`node --stack-size={bytes} lambda-local`
is enough.

**Comment by ashiina** [comment]
> Even with long code, the default nodejs stack size is enough if your program is well codded. If your code use too much memory, it surely is your code's fault.

> In some cases, if your code is really big (which would be strange for a lambda, due to the execution time) then you might want to increase the stack size, but it shouldn't be necessary...
> 
> To do that, the 
> node --stack-size={bytes} lambda-local
> is enough.

I agree with this, so I say `lamba-local` won't support this feature. 
You can always execute `node --stack-size={bytes} lambda-local` so it's not like you don't have any options. 

Closing
