### ISSUE TITLE
Run a folder as http server

### ISSUE THREAD

**Issue by cosbgn** [ashiina/lambda-local#212]
Hi,

ON my project I have an `/api` folder with inside a few files like:"

- file_one.js
- file_two.js
- etc

Each file is a lambda functions, something like this:
```
exports.handler = async (event, context) => {
	return  {
	  statusCode: 200,
	  headers: { 'Content-Type': 'application/json' },
	  body: JSON.stringify({ message: "Hello from file_one" })
	}
}
```

I would like to start a http local server which would map:

- http://localhost:8888/api/file_one => to file_one.js
- http://localhost:8888/api/file_two => to file_two.js
- etc

Is this possible?

**Comment by gpotter2** [comment]
Hi,
This is slighly too high level for lambda-local, and currently not implemented. It would however be easy to implement something like that yourself using a NodeJS `http.server` object, and calling `lambda-local` through it.
Have a good day
