### ISSUE TITLE
Allow object in clientContext

### ISSUE THREAD

**Issue by boblund** [ashiina/lambda-local#223]
I'm using lambda-local for a local API gateway websocket server. I want to use clientContext to pass a local version of AWS.ApiGatewayManagementApi.postToConnection() to the lambda integration. I can do this with the following change:
```
function _executeSync(opts) {
  ...
  clientContext = opts.clientContext; //JSON.parse(opts.clientContext);
```
i.e. don't parse the clientContext option.

Could this be a permanent change? I don't see a downside.

**Comment by gpotter2** [comment]
Fixed in 2.0.3 ! sorry for the delay
