### ISSUE TITLE
Update package.json engines

### ISSUE THREAD

**Issue by david-luna** [ashiina/lambda-local#235]
Hi,

Latest [release 2.1.0](https://github.com/ashiina/lambda-local/releases/tag/release%2F2.1.0) added support for lambda streaming which is pretty neat :)

I see the `package.json` file declares it supports node >=6 in the [engines section](https://github.com/ashiina/lambda-local/blob/f68eac1a0e040f4fe18866b9864676e168fc8de5/package.json#L36). But on the streaming related files the package is using `globalThis` symbol [here](https://github.com/ashiina/lambda-local/blob/f68eac1a0e040f4fe18866b9864676e168fc8de5/src/lib/streaming.ts#L61).

This symbol is available from version 12.4.0 according to [node.green](https://node.green/#ES2020-features-globalThis--globalThis--global-property-is-global-object) so I guess `engines` should be updated. I'm wondering if there is a way to make it still work in node 6.

Thanks

**Comment by gpotter2** [comment]
Thanks for the report !
Arguably, we should probably drop support for anything <= 8, as it is starting to be seriously out of date. But I'll have a look at how we can maximize support.

What do you think of https://github.com/ashiina/lambda-local/pull/236 ?

**Comment by david-luna** [comment]
Hi @gpotter2,

Sorry for the late reply. The change looks neat and stills support a wide version range :)

Thank you very much!
