### ISSUE TITLE
Regex doesn't parse my AWS credentials properly

### ISSUE THREAD

**Issue by croesus** [ashiina/lambda-local#24]
My AWS credentials file looks like this:
```
[default]
aws_access_key_id = ABCXYZ123
aws_secret_access_key = ABCXYZ123
```
Note the space either side of the equals. This fails the regex tests in `utils.js` lines 39 and 47. I'm pretty sure this was generated by aws-cli rather than hand edited, so others may have the same format.

Should be an easy fix to update the regex to ignore whitespace before/after the equals sign.

**Comment by ashiina** [comment]
True. Will get this fix!

**Comment by gpotter2** [comment]
Dumb error: spaces were not allowed in the regex...

**Comment by zackperdue** [comment]
lets merge this in

**Comment by ashiina** [comment]
done! thanks @gpotter2 !
