### ISSUE TITLE
Why is streamifyResponse polyfill missing an argument?

### ISSUE THREAD

**Issue by jayarjo** [ashiina/lambda-local#244]
I see that you have a polyfill for `streamifyResponse`, but why does it [receive only event and context](https://github.com/ashiina/lambda-local/blob/develop/src/lib/streaming.ts#L12), when even in the AWS blog post that it references `streamifyResponse` is supposed to receive three arguments, responseStream being the second?

**Comment by gpotter2** [comment]
That's incorrect. `streamifyResponse` accepts:

> a function that accepts the following parameters

See for instance how we use it in our tests: https://github.com/ashiina/lambda-local/blob/develop/test/functs/test-func-streaming.js
