### ISSUE TITLE
Error: Cannot find module 'aws-sdk'

### ISSUE THREAD

**Issue by croesus** [ashiina/lambda-local#25]
I want to test a Lambda function that uses `aws-sdk`. It looks like this should be supported by lambda-local but I'm getting the following error:

```
croesus$ lambda-local -l index.js -h handler -e ../events/MyLambdaFunctionEvent.js -p ~/.aws/credentials
Loading function
module.js:327
    throw err;
    ^

Error: Cannot find module 'aws-sdk'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/path/MyLambdaFunction/index.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```
I don't have `aws-sdk` installed locally within my Lambda package. I thought lambda-local would pick up its own packaged copy. Is there an environment variable I'm missing that tells node to look in the globally-installed lambda-local module for aws-sdk? I tried installing aws-sdk directly with `npm install -g aws-sdk` but that made no difference.

On macOS El Capitan, node 4.4.5, npm 2.15.5

**Comment by ashiina** [comment]
https://github.com/ashiina/lambda-local/blob/develop/package.json#L18
As seen here, lambda-local will install `aws-sdk` as part of its dependencies, during its install.

Can you check if you have `node_modules` located where your lambda-local is? Like this:

```
# In lambda-local 's directory
$ ls node_modules/
aws-sdk		commander	mocha
```

**Comment by croesus** [comment]
It's there:

```
croesus$ ls /usr/local/lib/node_modules/lambda-local/node_modules
aws-sdk		commander	fs		mocha
```

I've found a temporary workaround which may also provide a clue. I changed the require to use the full path to lambda-local's version of aws-sdk and the function loaded correctly.

```
var AWS = require('/usr/local/lib/node_modules/lambda-local/node_modules/aws-sdk');
```
The original version (and the one I need for the function in AWS) is:
```
var AWS = require('aws-sdk');
```

**Comment by croesus** [comment]
While my workaround allowed the module to load, calls to AWS functions are failing. I can see properties of the objects e.g. `dynamodb.endpoint.href` returns the correct value but calls to DynamoDB functions never call their callback functions e.g.
```
var key='123;
dynamodb.getItem({
  TableName: config.DDB_TABLE,
  Key: { key: { S: key } }
  }, function(err, data) {
    // This log is never reached
    console.log('Function returned err: ' + err);
  });
```

The code is working in the AWS environment.

**Comment by ashiina** [comment]
This sounds not like a `lambda-local` problem, but more like just a problem with your loading `aws-sdk`.
`lambda-local` isn't doing anything fancy other than using the normal `require()` of node.js.

Please try setting up a new node.js project for yourself and try requiring `aws-sdk`, and see if that works for you.

**Comment by croesus** [comment]
Thanks. I hadn't realized that node specifically doesn't support global modules (cf [http://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module](http://stackoverflow.com/questions/7970793/how-do-i-import-global-modules-in-node-i-get-error-cannot-find-module-module)).

 `npm link aws-sdk` creates a symbolic link from `./node_modules/aws-sdk` to (in my case) `/usr/local/lib/node_modules/aws-sdk` so the the `require()` works correctly. It means I need to exclude the local node_modules directory when I create the Lambda zip, but that's ok.

I still can't get any DynamoDB code to execute locally though. I'll post another question about that so we can close off this thread.

**Comment by ashiina** [comment]
Closing this thread! The DynamoDB issue is also fixed.

**Comment by motoko89** [comment]
It looks like adding `"moduleResolution": "node"` into `tsconfig.json` solve the problem for me
