### ISSUE TITLE
Please add region to the command line arguments

### ISSUE THREAD

**Issue by croesus** [ashiina/lambda-local#26]
Possibly related to my other problems, `aws-sdk` doesn't pick up a default region for me. For now, so I don't have to rebuild the compiled command I've hacked `lib/utils.js` to add
```
process.env['AWS_REGION'] = 'eu-west-1';
```
as a workaround.

**Comment by croesus** [comment]
Another workaround for this is to directly set the region in the Lambda code:
```
AWS.config.update({region: 'eu-west-1'});
```
It would still be preferable to have this specified "outside" the function to mirror the AWS environment.

**Comment by ChristopheBougere** [comment]
Yes a default region in lambda-local config/parameters would be great to avoid adding dev specific code :)
Meanwhile I use the same workaround: `AWS.config.update({region: 'eu-west-1'});`

**Comment by ashiina** [comment]
Thanks to @HerveNivon , this feature is now added with the `-r` option! Will release this in the next version.
