### ISSUE TITLE
There is an error when using the context.succeed function 

### ISSUE THREAD

**Issue by xtianus79** [ashiina/lambda-local#3]
Perhaps the sdk needs an update... but when running the function and it gets to the success context it has a TypeError.

**Comment by ashiina** [comment]
Sorry but I cannot seem to replicate this. Can you provide me with details? (Ideally with a code from your actual lambda function
)

**Comment by imhassan** [comment]
I am also getting  'undefined' error when calling context.fail() function. May be there is SDK update for that. but don't know why it is giving error on local but working in lamda-aws-console.

`exports.handler = function(event, context) {
	var email = event.email;
if(email == ""){
context.fail('Error in params');
}
});`

**Comment by ashiina** [comment]
@xtianus79  @imhassan 
I've tried looking into this. I am trying this code (based on @imhassan 's):

```
exports.handler = function(event, context) { 
	var email = event.email; 
	if(email == ""){ 
		context.fail('Error in params'); 
	} else {
		context.succeed('yay!');
	}
};
```

This seems to work normally in my environment - when I pass an `email` with an empty string in the event, I properly get the "Error in params".
Otherwise I get "yay!". 

Please try this lambda function, and tell me if it works or not.

**Comment by gpotter2** [comment]
@xtianus79 @imhassan 
Every thing's working fine. It only means you the 'context' you're using here is undefined. Perhaps you wrongly defined your exports.handler function. You should have to look at that. If you want a good tutorial, you can look at this one:
[http://www.jayway.com/2015/11/07/error-handling-in-api-gateway-and-aws-lambda/](http://www.jayway.com/2015/11/07/error-handling-in-api-gateway-and-aws-lambda/)

**Comment by ashiina** [comment]
Yep, will be closing this one
