### ISSUE TITLE
event path does not work in windows

### ISSUE THREAD

**Issue by tentkotta** [ashiina/lambda-local#32]
Hi,
The path to event.js file is not constructed properly in windows.
Please fix it.

**Comment by ashiina** [comment]
I would need more information to reproduce this. 
Please let me know what your input is, where your files are placed, and what the error output is.

**Comment by svenbluege** [comment]
My command line for windows is this: 

```lambda-local -c -t 10 -l index.js -h handler -e event-samples/event.js```

Reading the event works for me.

**Comment by gpotter2** [comment]
Works for me too...

**Comment by ashiina** [comment]
Will close this issue. Please re-submit with a clear description of your environment and reproduction steps.
