### ISSUE TITLE
Callbacks seem to not work

### ISSUE THREAD

**Issue by svenbluege** [ashiina/lambda-local#34]
I have a strange behavior here executing handlers on my Windows command line. It seems like callbacks are not executed. I put together the most simplest example I can imagine. 

This is my handler: 
```
exports.handler = function(event, context, callback) {
	var f = function() { console.log("x"); setTimeout(f, 500); }
	f();
};
```

This is the output of the local call: 
```
$>lambda-local -l index.js -h handler -e event-samples/event.js
Logs
------
START RequestId: 43221ee0-9ca6-9d93-c5d6-0a73bf30ff21
x
```

My expected result would be a timeout or/and a lot of _x_ output. Can you imagine anything I'm doing wrong here?

**Comment by entreprenik2** [comment]
Maybe related to #27 ? There's a potential solution there that worked for me.

**Comment by svenbluege** [comment]
I missed the closed tickets :) That did the trick. Thx.

```lambda-local -c -l index.js -h handler -e event-samples/event.js ```
