### ISSUE TITLE
File streams not working.

### ISSUE THREAD

**Issue by unclewalter** [ashiina/lambda-local#37]
I'm trying to locally test a function, but whenever I try to write to files using streams, it creates the file, but it's blank. Works fine in regular NodeJS. But when I try with _lambda-local_ it doesn't work properly. 

This is some test code, which works on regular NodeJS:

``` javascript
var fs = require('fs');
var readableStream = fs.createReadStream('file1.txt');
var writableStream = fs.createWriteStream('./tmp/file2.txt');

readableStream.pipe(writableStream);

```

**Comment by gpotter2** [comment]
Hi,

This is most likely a relative path mistake: when using lambda local to execute a function, you must specify the paths either relatively or absolutely from the file that you are using, as it's an exernal program.

For instance, this:
`var readableStream = fs.createReadStream('file1.txt');`
Should have been replaced by something like:
`var readableStream = fs.createReadStream('./file1.txt');`
or
`var readableStream = fs.createReadStream('/home/user/folder/file1.txt');`

Can you try this and tell us if it works ?

**Comment by gpotter2** [comment]
I guess it can be closed

**Comment by ashiina** [comment]
Closing since it is not related to lambda-local
