### ISSUE TITLE
Proposed functionality: Allow for the selection for .aws profile / credentials like the manual invocation of the lambda function

### ISSUE THREAD

**Issue by xtianus79** [ashiina/lambda-local#4]
instead of hard coding the profile in the .bash_profile... it would be nice if the param can mimi the aws-lambda function such that it will do a --profile aws_user_profile 

that would be great.

**Comment by ashiina** [comment]
Hey thanks for the feedback. I also hate having to do this too. I haven't looked into it far enough so I'll have to do a bit of research on how to make this happen; 
The dirtiest & simplest way will be to just read the `.aws` profile somewhere in `bin/lambda-local`.
Can you please enlighten me if there is a smarter approach?

**Comment by gpotter2** [comment]
Instead of forcing the user to rename his file and set it inside `bin/lambda-local`, I guess we can do as xtianus said :smiley: so i added a parameter "-p" here https://github.com/ashiina/lambda-local/pull/20 to select the profile location.

**Comment by ashiina** [comment]
merged @gpotter2 's PR, and now the feature is here :)
