### ISSUE TITLE
Publish 0.0.6 to npm

### ISSUE THREAD

**Issue by elgrom** [ashiina/lambda-local#5]
Any chance you could run npm publish on the new changes which include the ability to access context.fail? I see you have updated the GitHub to reflect these changes to 0.0.6 but npm is still at version 0.0.5. I have hacked my local files to update but would be good to have it come from NPM. Thanks for all of your efforts on this.

**Comment by ashiina** [comment]
Sorry about this. I will get to it ASAP

**Comment by elgrom** [comment]
Much appreciated, have a nice day.

**Comment by ashiina** [comment]
Sorry to have you waiting, I have published 0.0.6 !
https://www.npmjs.com/package/lambda-local
