### ISSUE TITLE
how to test lambda func via mocking

### ISSUE THREAD

**Issue by nqd** [ashiina/lambda-local#50]
Hello,

This is a question instead of a reported issue, please please keep reading.

lambda-local is great, and I am expecting to provide CDC test for lambda func via lambda-local. Still find hard way to mock a function. Ex:
lambda function -- require foo -- require bar; how to mock bar.abc function with, say, sinon?

Could you please give me some hint on this? Many thanks.

**Comment by nqd** [comment]
hi @ashiina, any suggestion :).

**Comment by gpotter2** [comment]
Hi,
So what you mean, is that you can't really access the lambda function before executing it right ?
Cause if, for instance, you could first generate the lambda handler, then modify stuff Inside it, and then pass it to lambda-local to run it, it would fix your problem ?

That is not included now in lambda-local, even if it could easily be, and it looks like your suggestion isn't that bad....

**Comment by gpotter2** [comment]
So I published a PR. It allows you to use, with [SinonJS](http://sinonjs.org/) (easiest way to mock), assuming you are using [mocha](https://mochajs.org/):

```
    var done, err;
    before(function (cb) {
        var lambdalocal = require("path_to_lambdalocal.js");
        lambdalocal.setLogger(your_winston_logger);
        var lambdaFunc = require("path_to_test-function.js");
        sinon.mock(lambdaFunc).expects("getData").returns("MockedData"); //see on sinonjs page for more options
        lambdalocal.execute({
            event: require(path.join(__dirname, "path_to_event.js")),
            lambdaFunc: lambdaFunc,
            lambdaHandler: "handler",
            callbackWaitsForEmptyEventLoop: true,
            timeoutMs: 3000,
            callback: function (_err, _done) {
                err = _err;
                done = _done;
                cb();
            }
        });
        describe("Your tests", function () {
            it("should return mocked value", function () {
                assert.equal(done, "MockedData");
            });
        });
    });
```

**Comment by nqd** [comment]
wao, so impressive for the pr and your effort.

great thanks, i will look into this (and ping you back if get into something ;) )

thanks again.
