### ISSUE TITLE
Option to disable logger

### ISSUE THREAD

**Issue by yosriady** [ashiina/lambda-local#53]
What do you think of providing an option to disable these logs?

https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L79-L82
```
    logger.log('info', 'Logs');
    logger.log('info', '------');
    logger.log('info', 'START RequestId: ' + context.awsRequestId);
```

I'd like to minimize the number of logs, and these logs do not add any value to my application.

**Comment by gpotter2** [comment]
It already exists !

You might use the function https://github.com/ashiina/lambda-local#setloggerlogger to set a custom winston logger, which will be used by lambda-local. If you set the logger level to 'error', you won't have all those logs...

Please read the full doc before asking a question.

**Comment by yosriady** [comment]
@gpotter2 Thank you.

**Comment by yosriady** [comment]
Pardon me for reopening this issue, but what's your recommended approach to logs when running unit tests calling local lambdas? Seeing the `lambda-local` source code as it is and if I understand correctly, there is no way to completely disable logs.

Using the default logger, everything from `lambda-local` is being logged, like so:

```
info: Logs
info: ------
info: START RequestId: 7c321442-6131-1300-89f1-16251d6453c4
info: END
error: Error
error: ------
info: {
	"statusCode": 500,
	"message": "Internal server error"
}
```

If we use a custom `error` level `winston` with `setLogger` as @gpotter2 suggests, error cases will still be logged. I see [this method](https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L12-L13) being done in `lambda-local` unit tests, but surely the [error logs](https://github.com/ashiina/lambda-local/blob/develop/lib/context.js#L101-L104) will still be logged regardless?

I'd like to **completely** disable logging (include `error`) from `lambda-local`. Are there currently ways to do this that I'm missing?

Ideally, we can do something like this:

```
lambdaLocal.execute({
  lambdaPath,
  lambdaHandler,
  logs: false,
});
```

**Comment by gpotter2** [comment]
I understand what you mean... it'a no a common request but you may still do it by editing the Winston logger:
If you set your custom logs levels, you may put all the usual log levels (error, warning, info, issue) and add another custom one before (none) for instance.

Then setting the log level to "none" will not even show the errors.

Hope it helped

**Comment by gpotter2** [comment]
So have you tried something like:

```
var winston = require("winston");
var my_levels = {levels: {none: 0, error: 1, warn: 2, info: 3, verbose: 4, debug: 5, silly: 6}};
winston.setLevels(my_levels);
winston.level = "none";
```
