### ISSUE TITLE
An invalid object is passed into Logger

### ISSUE THREAD

**Issue by ashiina** [ashiina/lambda-local#54]
I tried installing lambda-local from scratch and running it, and couldn't start it due to the following error.

```
$ node ./bin/lambda-local 
error: uncaughtException: The object must be a winston logger ! 
```

I realized that the `setLogger` function is expecting a `winston` function, but `lambda-local` is actually passing a `winston.Logger` object.
https://github.com/ashiina/lambda-local/blob/develop/bin/lambda-local#L11
https://github.com/ashiina/lambda-local/blob/develop/bin/lambda-local#L20

The test code is passing a `winston` object, so the actual code and test code are different. 
https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L12
https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L36

I am not sure why I missed this until now... but `lambda-local` does not seem to be correctly working from clean install right now, so I am submitting a PR immediately.

**Comment by ashiina** [comment]
@gpotter2 
I would appreciate it if you can check over this issue & PR, and let me know if I am doing something wrong. Thanks!

**Comment by gpotter2** [comment]
Wow I'm sorry for not having noticed that before...

**Comment by ashiina** [comment]
@gpotter2 No need to apologize, I missed it too... 
The real reason why this bug has been here until now is because an invalid logger object outputs an error, and we didn't have test code to guarantee that `bin/lambda-local` was passing the correct logger object. 

I believe there are two ways to prevent this sort of bug in the future:

### 1. Have test code for `bin/lambda-local`
This may be rather difficult since we cannot do it in the realm of our current test code, but may be needed in the future

### 2. Don't spit out errors for invalid logger objects
Logger objects aren't a critical part of this application, so when an invalid logger object is passed in `setLogger`, how about we just let it fall back to a default logger, as such?:

```
var _setLogger = function(_logger){
    if(_logger != null && typeof _logger.loggers != 'undefined'){
        logger = _logger;
    } else {
        // falling back to default logger (winston)
        logger = require('winston');
    }
}
```

**Comment by gpotter2** [comment]
Right, and you might as well log an error with it, to provide feedback...

**Comment by gpotter2** [comment]
@ashiina I guess it is, or maybe console.warn() is more accurate

**Comment by ashiina** [comment]
@gpotter2 Agreed. Thanks for your quick reply, I really appreciate it :)
Will add this to the PR

**Comment by ashiina** [comment]
complete
