### ISSUE TITLE
Set custom environment variables

### ISSUE THREAD

**Issue by kj187** [ashiina/lambda-local#58]
It would be great to add also env variables 
https://aws.amazon.com/de/about-aws/whats-new/2016/11/aws-lambda-supports-environment-variables/

Example:
$ lambda-local -l function.js -h handler -e event_samples.json -E "firstname:julian,lastname:kleinhans"

or
$ lambda-local -l function.js -h handler -e event_samples.json -env-var="firstname:julian,lastname:kleinhans"

I can contribute this feature in next few weeks if I have some more time

**Comment by gpotter2** [comment]
Hey,

I agree that lambda-local should support this feature. But we need to find a relevent format to pass them...

For instance, the format you've specified : "firstname:julian,lastname:kleinhans", is really incomplete...
What if my variable is `var dude="2\"@%^?"`

I'm guessing we'll support it with JSON, what do you think ?

Thanks anyway for reporting this problem 😃

**Comment by QAnders** [comment]
+1

**Comment by rodgersTR** [comment]
Made a little fix for environment variables, used JSON.  Pull request is up.

**Comment by ashiina** [comment]
merged!
