### ISSUE TITLE
Error: Use of const in strict mode

### ISSUE THREAD

**Issue by gabrielkaputa** [ashiina/lambda-local#59]
i tried this, this is what i got:

error: uncaughtException: /usr/local/lib/node_modules/lambda-local/lib/lambdalocal.js:11
const mute = require('mute'),
^^^^^
Use of const in strict mode.

is this a bug? can i solve this somehow? thanks!

**Comment by gpotter2** [comment]
As you can see, on line 1:
`'use strict';`

Which means that it is starting in strict mode... 

Which NodeJS version are you using ?, Are you using the latest lambda-local version ?

https://travis-ci.org/ashiina/lambda-local

The last build was passing...

**Comment by gabrielkaputa** [comment]
im using node v0.12.16, i installed lambda-local via npm so i guess it was the latest

**Comment by gpotter2** [comment]
It explains all. Your node version doesn't support "const".
Lambda local won't work with it...
I highly recommand you to update your nodejs version

**Comment by gabrielkaputa** [comment]
ok cool, thanks!

**Comment by gpotter2** [comment]
If it works then, please close this thread.

**Comment by jluterek** [comment]
I hit this same issue, so I ran the update from https://aigeec.com/upgrading-your-version-of-nodejs-on-windows-10-bash/

**Comment by gabrielkaputa** [comment]
I solved it with this https://github.com/creationix/nvm/blob/master/README.markdown
