### ISSUE TITLE
uncaughtException: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by jluterek** [ashiina/lambda-local#64]
This error seems to be related to https://github.com/ashiina/lambda-local/pull/61

Line 51: environment = JSON.parse(program.environment),

program.environment is supposed to be an optional variable, so this line ends up attempting to parse a null variable.

If I run lambda-local -l index.js -h handler -e event-samples/test.js -E [] the issue goes away.

Either the documentation should be updated to make this argument required, or a check should be added in case the string is null or empty.

FULL ERROR MESSAGE:

error: uncaughtException: Unexpected token u in JSON at position 0 date=Wed Feb 08 2017 12:00:07 GMT-0500 (STD), pid=6808, uid=0, gid=0, cwd=/mnt/c/code/Screenshots/create2, execPath=/usr/bin/nodejs, version=v6.9.5, argv=[/usr/bin/nodejs, /usr/local/
bin/lambda-local, -l, index.js, -h, handler, -e, event-samples/test.js, -e, []], rss=21626880, heapTotal=11571200, heapUsed=6396832, loadavg=[0.5185546875, 0.57763671875, 0.5859375], uptime=3924, trace=[column=null, file=null, function=Object.parse, line=null, method=pars
e, native=true, column=28, file=/usr/local/lib/node_modules/lambda-local/bin/lambda-local, function=null, line=51, method=null, native=false, column=3, file=/usr/local/lib/node_modules/lambda-local/bin/lambda-local, function=, line=111, method=null, native=false, column=3
2, file=module.js, function=Module._compile, line=570, method=_compile, native=false, column=10, file=module.js, function=Object.Module._extensions..js, line=579, method=Module._extensions..js, native=false, column=32, file=module.js, function=Module.load, line=487, metho
d=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=446, method=null, native=false, column=3, file=module.js, function=Function.Module._load, line=438, method=Module._load, native=false, column=10, file=module.js, function=Module.runMain, line=60
4, method=runMain, native=false, column=7, file=bootstrap_node.js, function=run, line=394, method=null, native=false], stack=[SyntaxError: Unexpected token u in JSON at position 0,     at Object.parse (native),     at /usr/local/lib/node_modules/lambda-local/bin/lambda-lo
cal:51:28,     at Object.<anonymous> (/usr/local/lib/node_modules/lambda-local/bin/lambda-local:111:3),     at Module._compile (module.js:570:32),     at Object.Module._extensions..js (module.js:579:10),     at Module.load (module.js:487:32),     at tryModuleLoad (module.
js:446:12),     at Function.Module._load (module.js:438:3),     at Module.runMain (module.js:604:10),     at run (bootstrap_node.js:394:7)]

**Comment by jiefeng1115** [comment]
same

**Comment by gpotter2** [comment]
No one has checked that it worked before pushing it ? :man_facepalming:

**Comment by pselle** [comment]
Thank you for reporting this issue and how to get around it!

**Comment by gpotter2** [comment]
Does this https://github.com/ashiina/lambda-local/issues/64 fix it for you ?

**Comment by jiefeng1115** [comment]
@gpotter2 how do I check it?

**Comment by gpotter2** [comment]
@jiefeng1115 You download the modified file and replace the same one in your downloaded version with it. If it's too complicated for you do not worry :)
