### ISSUE TITLE
Need test for environment variable

### ISSUE THREAD

**Issue by ashiina** [ashiina/lambda-local#68]
There are no tests against the use of environment variables.
We should have some to increase the quality. 

(Apologies for my previous release with a critical bug... That was my responsibility)

**Comment by raphaellondner-mongodb** [comment]
So are environment variables supported as this stage? I tried using the -E parameter as such:

`lambda-local -l app.js -e event.json -E {"key1":"value1"}`

but it didn't work ("Unexpected token in JSON at position 1" error). 

@ashiina, can you provide a working example of the -E parameter syntax?

**Comment by ashiina** [comment]
@raphaellondner-mongodb Environment variables are supported! Your problem is simply not escaping your double-quotes. Your example will work like this:

```
lambda-local -l app.js -e event.json -E {\"key1\":\"value1\"}
```

I'll add this in the README to avoid future confusion

**Comment by raphaellondner-mongodb** [comment]
Thanks @ashiina. To be clear, environment variables aren't available outside of the handler function (though they seem to be in AWS Lambda), is that a correct assumption?

Practically, I'd like to instantiate my variable before the exports.handler function with:

var param = process.env['key1'];

but the param variable is undefined when referenced from the handler code and lambda-local is used. It is populated with the proper value when run directly in AWS Lambda though.

**Comment by ashiina** [comment]
@raphaellondner-mongodb 
> To be clear, environment variables aren't available outside of the handler function (though they seem to be in AWS Lambda), is that a correct assumption?

Just looked into this now, and yeah it seems like it isn't available... The reason is that, in our current `lambda-local` code, setting environment variables is done AFTER requiring the lambda code.
And code outside of the function is executed the instant it is required.

 * require lambda function
https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L59
 * set env vars
https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L84

This looks like an easy fix, so I'll work on it and get it fixed up ASAP :)

**Comment by ashiina** [comment]
done, merged
https://github.com/ashiina/lambda-local/pull/71

**Comment by ashiina** [comment]
It's in the `develop` branch, and will publish this as a new version within a few days (after a little more dog-fooding)!
