### ISSUE TITLE
Link for Executing Lambda Local within another Node Script in Docs

### ISSUE THREAD

**Issue by iamkirkbater** [ashiina/lambda-local#74]
Hi.  I was going through the readme and when I got to the part about running lambda local in another node script the MochaJS link takes me to AWS docs, and I didn't explicitly see anything in particular about running lambda-local within another node script.  I went through the tests you have written and found this: https://github.com/ashiina/lambda-local/blob/develop/test/test.js#L61, which solves my problem, but I was wondering if the docs were supposed to be linking to something in particular on that page that I missed?  

Maybe it would be worth putting an example like the one above in the readme?  I wouldn't mind doing this, I just wanted to know if it's something that I missed in the link that is there, though, before I started on that.

Thanks!

**Comment by ashiina** [comment]
@iamkirkbater Hi! The node script example is inside this file
https://github.com/ashiina/lambda-local/blob/develop/REQUIRE_SAMPLES.md 
and we do have a link to this sample in the `README.md`: 
https://github.com/ashiina/lambda-local/blob/develop/README.md#samples

But assuming from your comment, you weren't able to find this. So given this information, do you think other people will also have trouble finding this? Should I expose the example on `README.md` ?

Would love to hear your opinion!

**Comment by iamkirkbater** [comment]
Ohh, I see it now all the way at the bottom in Samples. I didn't see that, I just saw the code samples there and thought that was it. Maybe just add another link to the samples where it talks about testing with Mocha instead of linking further down the page, or just merging the Samples and readme files together?


_____________________________

**Comment by ashiina** [comment]
@iamkirkbater Yeah maybe merging the SAMPLES might be simpler, less confusion. I'll get to it; Thanks for your comment!

**Comment by ashiina** [comment]
done https://github.com/ashiina/lambda-local/commit/44fecef8c5094dabd41dba74c8081eb8962c4653
