### ISSUE TITLE
Unexpected token import - ES6

### ISSUE THREAD

**Issue by sharepointalex** [ashiina/lambda-local#75]
Now that AWS Lambda supports ES6, i've used Lebab to transpile my ES5 code to ES6.

It works fine on AWS Lambda however trying to use lambda-local against it I get 'Unexpected token import' when i'm using Import instead of using 'require'.

Does lambda-local support ES6 yet?

**Comment by hoegertn** [comment]
How are you packaging your code for Lambda and how do you run it locally? NodeJS does not support "import" natively. So maybe there is some transpiling happening before uploading it to AWS.

**Comment by sharepointalex** [comment]
@hoegertn thanks - I didn't realise NodeJS didn't support "import" natively - planning to compile through babel now in a built script in package.json - thanks!
