### ISSUE TITLE
Context is singleton, so concurrency is unsupported

### ISSUE THREAD

**Issue by garymcleanhall** [ashiina/lambda-local#79]
Because the `context` object is a singleton, it is not possible to have concurrent runs of the `lambda.execute` function: the context is overwritten and shenanigans ensue.

Also, if you have nested calls to `lambda.execute` (don't ask, it's a corner case), then the 1st callback is overwritten by the 2nd callback, and then the 2nd callback is erroneously called after completion of the 1st call.

When using promises, this caused a livelock. When using callbacks, I ultimately got errors from express because 'headers have already been written' - the closure for the route was referencing the original `response` object.

I'll raise a PR to fix this.

**Comment by gpotter2** [comment]
Hi !
Any news on this ?
