### ISSUE TITLE
InvalidToken during AWS calls

### ISSUE THREAD

**Issue by edthorne** [ashiina/lambda-local#82]
I think the following commit's ordering of environment variables has caused an issue with executing AWS API calls:

5764912ae9d74688f55ba6f2daac7e1c2cb6f294

The author moved the require for external functions below the setting of AWS_SESSION_TOKEN and custom environment variables. This had the effect of making this token visible to the AWS SDK loaded in the require. Since this token is only valid when using temporary credentials, it causes regular credential requests to fail.

See [this AWS Security Blog Post](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/)

**Comment by gpotter2** [comment]
So basically, would simply removing the line: https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L93 be enough ?

This line is left from the time were we had not added a credential support, and we used to generate random values. Now we got https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L72 instead.

**Comment by edthorne** [comment]
I will disagree with you on the ordering. Previously, the variable was not set in the environment when the AWS SDK was sourced by the target Lambda under test. Thus, it was not part of the AWS configuration at the time the module was loaded and not included in the requests going to AWS. It was set in the environment after the AWS SDK was sourced, thus it wasn't part of the SDK's configuration and everything worked in version 1.4.1.

I commented on your pull request. Handling of the optional AWS_SESSION_TOKEN should probably be done in Utils._loadCredentials rather than outright removal. It is present in a normal Lambda environment and some testing could possibly require its use. Thanks for submitting a fix.

**Comment by shabbyrobe** [comment]
I'm getting this same error, when trying to download a file from S3. Removing this line fixes it: https://github.com/ashiina/lambda-local/blob/develop/lib/lambdalocal.js#L93

**Comment by gpotter2** [comment]
Yes, here's the fix: https://github.com/ashiina/lambda-local/pull/85
It simply have not been acceped yet... sorry for that :/

**Comment by gpotter2** [comment]
Hi had this been fixed ?

**Comment by edthorne** [comment]
I don't think it's been released.

**Comment by alexkrolick** [comment]
This is mutating the AWS module globally - if you try to download signed S3 objects subsequently, it fails. This fix really needs to be released.

**Comment by gpotter2** [comment]
New npm version released
