### ISSUE TITLE
errors are ugly, but ...

### ISSUE THREAD

**Issue by Opticsponge** [ashiina/lambda-local#86]
I am loving this, but am finding global errors super hard to read.. so before I start looking for a solution for my issue, I thought I would reach out and see if anyone has solved UX issue with human readable errors.

**Comment by gpotter2** [comment]
Hi,
Error prints should have been fixed with the last versions.

If you still find it hard to read, we'll be soon changing the log system to clarify it so bare with us ...

**Comment by gpotter2** [comment]
Hi
sorry for the delay, there's now a proper nice verbose system available !
Please have a look at the updated Readme for the parameter verboseLevel

Thanks !
