### ISSUE TITLE
error: unknown option `--envfile'

### ISSUE THREAD

**Issue by cosmini** [ashiina/lambda-local#90]
Here is the command I'm trying to run:
`lambda-local -l index.js -e event.json -t 10 --envfile .env`

And without the `--envfile`it was running well, provided that I used the _dotenv_ library into my script.
I thought that would be better if I simulate lambda as close as it is in AWS and make use of your env file option.
I know that it works with JSON payload as `-E`, but I'm not really interested in that.
Any idea why this is happening? Thanks.

Otherwise all is great and thanks for sharing this good library.

**Comment by epool** [comment]
This seems to me implemented in `develop` branch but not in master, so probably this is not released yet for some reason =/

**Comment by petermoser** [comment]
It is still not working when installing the latest using:
npm install -g lambda-local

To make the --envfile option work, I had to clone the project and copy the files to:
/usr/local/lib/node_modules/lambda-local/

**Comment by gpotter2** [comment]
New npm version released
