### ISSUE TITLE
Callback parameters are optional

### ISSUE THREAD

**Issue by csimi** [ashiina/lambda-local#92]
Source: http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback

So checking for errors like this is going to break a lot of lambdas that are actually running with no issues on AWS:
```
if (err === null) {
```
or
```
if (err !== null) {
```

This code also runs successfully:
```
callback(undefined, 'Hello from Lambda');
```

This reports error, so it's not just a simple truthy/falsy check:
```
callback(0, 'Hello from Lambda');
```

**Comment by gpotter2** [comment]
Was this fixed in the latest dev version ?
(`develop` branch)

Thanks!
