### ISSUE TITLE
Lambda@Edge

### ISSUE THREAD

**Issue by chrisvdb** [ashiina/lambda-local#93]
Would it be possible to include an example for Lambda@Edge with CloudFront?

**Comment by chrisvdb** [comment]
No need for me, but might be useful for other people as Lambda@Edge is now GA.

**Comment by gpotter2** [comment]
Ok.

If you have used lambda local on that kind of tests, some examples/help would be greatly appreciated, as I'm not used to Lambda@Edge with CloudFront.

Thanks !

**Comment by chrisvdb** [comment]
Please find my example code [here](https://serverfault.com/questions/820939/hsts-on-amazon-cloudfront-from-s3-origin) (last answer).

**Comment by gpotter2** [comment]
Thank you, will look forward into this
